import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  // 1. تنظيف قاعدة البيانات أولاً
  await prisma.product.deleteMany({});
  await prisma.category.deleteMany({});

  // 2. إنشاء الأقسام المطلوبة
  const electronics = await prisma.category.create({
    data: { name: "إلكترونيات", slug: "electronics" },
  });

  const fashion = await prisma.category.create({
    data: { name: "الأزياء", slug: "fashion" },
  });

  const beauty = await prisma.category.create({
    data: { name: "الصحة والجمال", slug: "beauty" },
  });

  const accessories = await prisma.category.create({
    data: { name: "الإكسسوارات والأحذية", slug: "accessories" },
  });

  // 3. إضافة المنتجات المطلوبة
  await prisma.product.createMany({
    data: [
     
      {
        name: "هودي كاجوال كلاسيك رائع",
        slug: "men-casual-shirt",
        description: "قميص قطني مريح جداً مناسب لجميع الأوقات والخروجات.",
        price: 850,
        stock: 40,
        brand: "Zara",
        images: ["/images/products/2.jpg"],
        colors: ["bg-white", "bg-slate-500"],
        categoryId: fashion.id,
        rating: 4.2,
      },
      {
        name: "تي شيرت قطني صيفي خفيف",
        slug: "men-summer-tshirt",
        description: "تي شيرت كاجوال قطن 100% مناسب للأجواء الحارة.",
        price: 450,
        stock: 50,
        brand: "Nike",
        images: ["/images/products/2.jpg"],
        colors: ["bg-blue-700", "bg-black"],
        categoryId: fashion.id,
        rating: 4.5,
      },
      {
        name: "حزام جلد طبيعي كلاسيك",
        slug: "classic-leather-belt",
        description: "حزام من الجلد الطبيعي المتين مع إبزيم معدني مقاوم للصدأ.",
        price: 350,
        stock: 25,
        brand: "Timberland",
        images: ["/images/products/belt.jpg"],
        colors: ["bg-black", "bg-amber-900"],
        categoryId: fashion.id,
        rating: 4.4,
      },
      // 3 تي شيرتات حريمي
      {
        name: "تي شيرت حريمي مطبوع عصري",
        slug: "women-printed-tshirt",
        description: "تي شيرت حريمي بتصميم مريح وألوان مبهجة تناسب الجامعة والخروج.",
        price: 500,
        stock: 30,
        brand: "H&M",
        images: ["/images/products/clothes-1.jpg"],
        colors: ["bg-pink-500", "bg-white"],
        categoryId: fashion.id,
        rating: 4.6,
      },
      {
        name: "تي شيرت حريمي سادة كاجوال",
        slug: "women-plain-tshirt",
        description: "تي شيرت حريمي قطني سادة ناعم جداً على البشرة.",
        price: 420,
        stock: 35,
        brand: "Mango",
        images: ["/images/products/clothes-2.jpg"],
        colors: ["bg-red-500", "bg-black"],
        categoryId: fashion.id,
        rating: 4.3,
      },
      {
        name:"جيبة حريمة رائعة مطرزة",
        slug: "women-sports-tshirt",
        description: "جيبة حريمي أنيقة بتطريز دقيق، مناسبة للخروجات والمناسبات.",
        price: 600,
        stock: 20,
        brand: "Adidas",
        images: ["/images/products/clothes-3.jpg"],
        colors: ["bg-slate-400", "bg-blue-600"],
        categoryId: fashion.id,
        rating: 4.7,
      },
      // 6 جواكت
      {
        name: "جاكيت بامب شتوي ثقيل",
        slug: "winter-padded-jacket",
        description: "جاكيت شتوي مبطن بالفرو لعزل تام ضد البرد والمطر.",
        price: 2200,
        discountPrice: 1950,
        stock: 12,
        brand: "Town Team",
        images: ["/images/products/jacket-1.jpg"],
        colors: ["bg-black", "bg-blue-900"],
        categoryId: fashion.id,
        rating: 4.8,
      },
      {
        name: "جاكيت جينز كلاسيكي عصري",
        slug: "classic-denim-jacket",
        description: "جاكيت جينز متين يناسب مختلف الإطلالات الشبابية العصرية.",
        price: 1350,
        stock: 18,
        brand: "Levi's",
        images: ["/images/products/jacket-2.jpg"],
        colors: ["bg-blue-500"],
        categoryId: fashion.id,
        rating: 4.5,
      },
      {
        name: "جاكيت جلد طبيعي فاخر",
        slug: "luxury-leather-jacket",
        description: "جاكيت من الجلد الطبيعي 100% بتصميم راقٍ لعشاق الفخامة.",
        price: 3800,
        discountPrice: 3400,
        stock: 8,
        brand: "Zara",
        images: ["/images/products/jacket-3.jpg"],
        colors: ["bg-black", "bg-amber-900"],
        categoryId: fashion.id,
        rating: 4.9,
      },
      {
        name: "جاكيت صوف رسمي أنيق",
        slug: "formal-wool-jacket",
        description: "جاكيت صوف طويل مناسب للمناسبات الرسمية وبيئة العمل الشتوية.",
        price: 2600,
        stock: 10,
        brand: "G2000",
        images: ["/images/products/jacket-4.jpg"],
        colors: ["bg-slate-700", "bg-black"],
        categoryId: fashion.id,
        rating: 4.6,
      },
      {
        name: "جاكيت جباردين خفيف مبطن",
        slug: "lightweight-gabardine-jacket",
        description: "جاكيت خريفي خفيف الوزن ومريح للتنقل اليومي.",
        price: 1100,
        stock: 15,
        brand: "Pull&Bear",
        images: ["/images/products/jacket-5.jpg"],
        colors: ["bg-green-800", "bg-amber-700"],
        categoryId: fashion.id,
        rating: 4.2,
      },
      {
        name: "جاكيت رياضي مقاوم للرياح",
        slug: "sports-windbreaker-jacket",
        description: "جاكيت رياضي خفيف ومقاوم للمياه، مثالي للأجواء المتقلبة وللتمارين.",
        price: 950,
        stock: 22,
        brand: "Nike",
        images: ["/images/products/jacket-6.jpg"],
        colors: ["bg-orange-500", "bg-black"],
        categoryId: fashion.id,
        rating: 4.4,
      },

      {
        name: "شامبو مغذّي للشعر بالزيوت الطبيعية",
        slug: "nourishing-hair-shampoo",
        description: "ينظف الشعر بعمق ويمنحه اللمعان والقوة من الجذور وحتى الأطراف.",
        price: 250,
        stock: 60,
        brand: "L'Oreal",
        images: ["/images/products/shampoo.jpg"],
        colors: [],
        categoryId: beauty.id,
        rating: 4.3,
      },
      {
        name: "عطر فرنسي فواح وثابت",
        slug: "premium-french-perfume",
        description: "برفان ذو رائحة ساحرة تدوم طويلاً وتمنحك جاذبية لا تقاوم.",
        price: 1850,
        discountPrice: 1600,
        stock: 14,
        brand: "Dior",
        images: ["/images/products/perfume.jpg"],
        colors: [],
        categoryId: beauty.id,
        rating: 4.9,
      },
      {
        name: "جل الصبار الطبيعي المرطب جلوري",
        slug: "aloe-vera-moisturizer-gel",
        description: "جل مرطب ومهدئ للبشرة ومغذي ممتاز بعد التعرض للشمس.",
        price: 180,
        stock: 45,
        brand: "Glory",
        images: ["/images/products/shampoo.jpg"],
        colors: [],
        categoryId: beauty.id,
        rating: 4.5,
      },
      {
        name: "كريم تصفيف وتثبيت الشعر جلوري",
        slug: "hair-styling-cream-glory",
        description: "كريم لتثبيت الشعر طوال اليوم بلمعان طبيعي ودون ترك أي رواسب.",
        price: 220,
        stock: 50,
        brand: "Glory",
        images: ["/images/products/shampoo.jpg"],
        colors: [],
        categoryId: beauty.id,
        rating: 4.2,
      },
      {
        name: "سيروم العناية بالبشرة وإشراقتها جلوري",
        slug: "skin-glow-serum-glory",
        description: "سيروم غني بفيتامين C لتوحيد لون البشرة ومحاربة علامات الإرهاق.",
        price: 390,
        stock: 20,
        brand: "Glory",
        images: ["/images/products/shampoo.jpg"],
        colors: [],
        categoryId: beauty.id,
        rating: 4.7,
      },

      
      {
        name: "حذاء مشي مريح وخفيف - أسود",
        slug: "comfortable-walking-shoe-1",
        description: "شوز كاجوال مريح جداً ونعل طبي مرن للمشي مسافات طويلة.",
        price: 950,
        stock: 30,
        brand: "Skechers",
        images: ["/images/products/shoe-1.jpg"],
        colors: ["bg-black"],
        categoryId: accessories.id,
        rating: 4.8,
      },
      {
        name: "حذاء رياضي يومي - أبيض كلاسيك",
        slug: "daily-sneaker-white",
        description: "سنيكرز أنيق باللون الأبيض يتناسب مع الجينز والأزياء الكاجوال.",
        price: 1100,
        stock: 25,
        brand: "Adidas",
        images: ["/images/products/shoe-2.jpg"],
        colors: ["bg-white"],
        categoryId: accessories.id,
        rating: 4.6,
      },
      {
        name: "شوز جلد كلاسيك مريح",
        slug: "classic-leather-shoe",
        description: "حذاء مصنوع من الجلد عالي الجودة للمناسبات الرسمية والعمل.",
        price: 1400,
        stock: 15,
        brand: "Clarks",
        images: ["/images/products/shoe-3.jpg"],
        colors: ["bg-amber-950"],
        categoryId: accessories.id,
        rating: 4.4,
      },
      {
        name: "حذاء جري شبكي مسامي",
        slug: "mesh-running-shoe",
        description: "حذاء جري يتميز بتهوية ممتازة ونعل يمتص الصدمات.",
        price: 1250,
        stock: 20,
        brand: "Nike",
        images: ["/images/products/shoe-4.jpg"],
        colors: ["bg-blue-800"],
        categoryId: accessories.id,
        rating: 4.7,
      },
      {
        name: "حذاء قماشي خفيف للصيف",
        slug: "canvas-summer-shoe",
        description: "شوز قماش خفيف وسهل الارتداء يومياً في الصيف.",
        price: 550,
        stock: 40,
        brand: "Vans",
        images: ["/images/products/shoe-5.jpg"],
        colors: ["bg-slate-600"],
        categoryId: accessories.id,
        rating: 4.1,
      },
      {
        name: "حذاء رانينج عصري ألوان متداخلة",
        slug: "modern-running-shoe",
        description: "شوز رياضي مريح بألوان مميزة وتصميم شبابي لافت.",
        price: 1300,
        stock: 15,
        brand: "Puma",
        images: ["/images/products/shoe-1.jpg"],
        colors: ["bg-orange-500", "bg-black"],
        categoryId: accessories.id,
        rating: 4.5,
      },
      
      // 6 شوز كورة
      {
        name: "حذاء كرة قدم للملاعب العشبية - بريداتور",
        slug: "football-shoes-predator",
        description: "شوز كورة احترافي يوفر تحكماً فائقاً بالكرة على الملاعب الطبيعية.",
        price: 2400,
        discountPrice: 2100,
        stock: 10,
        brand: "Adidas",
        images: ["/images/products/sports-1.jpg"],
        colors: ["bg-black", "bg-red-500"],
        categoryId: accessories.id,
        rating: 4.9,
      },
      {
        name: "حذاء خماسي للملاعب الترتان - ميركوريال",
        slug: "turf-football-shoes-mercurial",
        description: "حذاء خماسي بنعل مطاطي مخصص للملاعب الصناعية (الترتان).",
        price: 1950,
        stock: 14,
        brand: "Nike",
        images: ["/images/products/sports-2.jpg"],
        colors: ["bg-orange-500", "bg-white"],
        categoryId: accessories.id,
        rating: 4.8,
      },
      {
        name: "شوز كورة فيوتشر احترافي",
        slug: "football-shoes-puma-future",
        description: "تصميم انسيابي يوفر خفة وسرعة حركة عالية في الملعب.",
        price: 2150,
        stock: 8,
        brand: "Puma",
        images: ["/images/products/sports-3.jpg"],
        colors: ["bg-blue-600"],
        categoryId: accessories.id,
        rating: 4.6,
      },
      {
        name: "حذاء كرة قدم كلاسيكي جلد",
        slug: "classic-leather-football-shoe",
        description: "شوز كورة جلد طبيعي تقليدي للمتانة والراحة الفائقة.",
        price: 1600,
        stock: 12,
        brand: "Mizuno",
        images: ["/images/products/sports-4.jpg"],
        colors: ["bg-white", "bg-black"],
        categoryId: accessories.id,
        rating: 4.5,
      },
      {
        name: "حذاء خماسي ترتان خفيف السعر",
        slug: "budget-turf-football-shoe",
        description: "شوز ترتان ممتاز للتمارين والمباريات الودية الأسبوعية.",
        price: 850,
        stock: 25,
        brand: "Lotto",
        images: ["/images/products/sports-5.jpg"],
        colors: ["bg-green-600"],
        categoryId: accessories.id,
        rating: 4.2,
      },
      {
        name: "حذاء كرة قدم للصغار والناشئين",
        slug: "kids-football-shoe",
        description: "شوز كورة مريح ومبطن لحماية أقدام الناشئين أثناء اللعب.",
        price: 750,
        stock: 30,
        brand: "Umbro",
        images: ["/images/products/sports-6.jpg"],
        colors: ["bg-red-500", "bg-black"],
        categoryId: accessories.id,
        rating: 4.4,
      },

      {
        name: "ساعة ذكية رياضية متطورة بلس",
        slug: "smart-watch-sports-plus",
        description: "تتبع دقات القلب، الأكسجين، ومزودة بأكثر من 50 وضعاً رياضياً ومقاومة للماء.",
        price: 3200,
        discountPrice: 2850,
        stock: 15,
        brand: "Xiaomi",
        images: ["/images/products/watch-1.jpg"],
        colors: ["bg-black", "bg-slate-500"],
        categoryId: electronics.id,
        rating: 4.6,
      },
      {
        name: "ساعة ذكية شاشة أموليد فاخرة",
        slug: "premium-amoled-smartwatch",
        description: "شاشة Amoled فائقة الوضوح مع دعم كامل لإجراء واستقبال المكالمات.",
        price: 5400,
        stock: 9,
        brand: "Huawei",
        images: ["/images/products/watch-2.jpg"],
        colors: ["bg-black", "bg-amber-700"],
        categoryId: electronics.id,
        rating: 4.8,
      },
      {
        name: "ساعة ذكية اقتصادية بميزات متكاملة",
        slug: "budget-friendly-smartwatch",
        description: "أفضل قيمة مقابل سعر، بطارية تدوم حتى 10 أيام مع منبه وتنبيهات الرسائل.",
        price: 1350,
        stock: 20,
        brand: "Oraimo",
        images: ["/images/products/watch-3.jpg"],
        colors: ["bg-black", "bg-blue-900"],
        categoryId: electronics.id,
        rating: 4.3,
      },
    ],
  });

  console.log("✅ تم ملء قاعدة البيانات بالبيانات المطلوبة بنجاح!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });